---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "CaffeineJunkieX's 24-hour Charity Stream for Extra Life - November 7th"
keywords:    "twitch, extra-life, charity, ucsf benioff, marathon"
description: "24-hour Charity Gaming Stream to raise money for UCSF Benioff Children's Hospital hosted by St. John Johnson (CaffeineJunkieX)"
source_link: "https://github.com/stjohnjohnson/cjx.watch"
google_analytics_key: "G-Q18W9Y3HX7"

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#3daa27'
  red:       '#D3002A'
  purple:    '#a900b2'
  violet:    '#5D449E'
  orange:    '#bc740f'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

